# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contest',
            new_name='PastContest',
        ),
    ]
