# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20160407_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
