# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20160421_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(to='coding.Skill'),
        ),
    ]
